---
  - name: Add EPEL repository
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

  - name: Add REMI PHP 7.X repository
    yum:
      name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"

  - selinux:
      state: disabled

  - name: Install php-fpm 7.0/7.1/7.2/7.3
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - nginx
        - certbot
        - certbot-nginx
        - php70-php-fpm
        - php71-php-fpm
        - php72-php-fpm
        - php73-php-fpm

  - name: install "MariaDB" package
    yum:
       name: mariadb-server
       state: latest
    notify: mariadb start

  - name: adding port 9000 for php 7.0
    shell: sed -i 's/:9000/:9000/' /etc/opt/remi/php70/php-fpm.d/www.conf

  - name: adding port 9001 for php7.1
    shell: sed -i 's/:9000/:9001/' /etc/opt/remi/php71/php-fpm.d/www.conf

  - name: adding port 9002 for php7.2
    shell: sed -i 's/:9000/:9002/' /etc/opt/remi/php72/php-fpm.d/www.conf

  - name: adding port 9003 for php7.3
    shell: sed -i 's/:9000/:9003/' /etc/opt/remi/php73/php-fpm.d/www.conf

  - name: Adding nginx as user and group to PHP-FPM config files
    replace:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { path: '/etc/opt/remi/php70/php-fpm.d/www.conf', regexp1: 'apache', replace: 'nginx'}
      - { path: '/etc/opt/remi/php71/php-fpm.d/www.conf', regexp1: 'apache', replace: 'nginx'}
      - { path: '/etc/opt/remi/php72/php-fpm.d/www.conf', regexp1: 'apache', replace: 'nginx'}
      - { path: '/etc/opt/remi/php73/php-fpm.d/www.conf', regexp1: 'apache', replace: 'nginx'}

  - name: copy the nginx default
    template:
        src: /etc/ansible/roles/ansible-multi-php-c7/files/default.j2
        dest: /etc/nginx/conf.d/default.conf
    become: yes

  - name: copy the nginx.conf
    copy:
      src: /etc/ansible/roles/ansible-multi-php-c7/files/nginx.conf
      dest: /etc/nginx/nginx.conf
    become: yes

  - name: copy the nginx SSL config
    copy:
      src: /etc/ansible/roles/ansible-multi-php-c7/files/ssl.conf
      dest: /etc/nginx/conf.d/ssl.conf
    become: yes

  - name: copying 1.php file for phpinfo
    copy:
      src: /etc/ansible/roles/ansible-multi-php-c7/files/1.php
      dest: /var/www/html/
    become: yes
    notify: nginx start

  - name: start php7.0 FPM
    service: name=php70-php-fpm state=started

  - name: start php7.1 FPM
    service: name=php71-php-fpm state=started

  - name: start php7.2 FPM
    service: name=php72-php-fpm state=started

  - name: start php7.3 FPM
    service: name=php73-php-fpm state=started

  - name: add to autostart nginx
    systemd:
      name: nginx
      enabled: yes
      masked: no

  - name: add to autostart PHP70-FPM
    systemd:
      name: php70-php-fpm
      enabled: yes
      masked: no

  - name: add to autostart PHP71-FPM
    systemd:
      name: php71-php-fpm
      enabled: yes
      masked: no 

  - name: add to autostart PHP72-FPM
    systemd:
      name: php72-php-fpm
      enabled: yes
      masked: no

  - name: add to autostart PHP73-FPM
    systemd:
      name: php73-php-fpm
      enabled: yes
      masked: no

  - name: add to autostart MariaDB
    systemd:
      name: mariadb
      enabled: yes
      masked: no